In [2]:
from transformers import BertTokenizer 
tokenizer = BertTokenizer.from_pretrained('bert-base-uncased') 
text = "BERT preprocessing is essential." 
tokens = tokenizer.tokenize(text) 
print(tokens)

c:\Users\石天辰\.conda\envs\pytorch\lib\site-packages\huggingface_hub\file_download.py:159: UserWarning: `huggingface_hub` cache-system uses symlinks by default to efficiently store duplicated files but your machine does not support them in C:\Users\石天辰\.cache\huggingface\hub\models--bert-base-uncased. Caching files will still work but in a degraded version that might require more space on your disk. This warning can be disabled by setting the `HF_HUB_DISABLE_SYMLINKS_WARNING` environment variable. For more details, see https://huggingface.co/docs/huggingface_hub/how-to-cache#limitations.
To support symlinks on Windows, you either need to activate Developer Mode or to run Python as an administrator. In order to see activate developer mode, see this article: https://docs.microsoft.com/en-us/windows/apps/get-started/enable-your-device-for-development
  warnings.warn(message)


['bert', 'prep', '##ro', '##ces', '##sing', 'is', 'essential', '.']


c:\Users\石天辰\.conda\envs\pytorch\lib\site-packages\transformers\tokenization_utils_base.py:1601: FutureWarning: `clean_up_tokenization_spaces` was not set. It will be set to `True` by default. This behavior will be depracted in transformers v4.45, and will be then set to `False` by default. For more details check this issue: https://github.com/huggingface/transformers/issues/31884
  warnings.warn(


In [3]:
from transformers import BertForSequenceClassification,BertTokenizer 
import torch 
tokenizer = BertTokenizer.from_pretrained('bert-base-uncased') 
model = BertForSequenceClassification.from_pretrained('bert-base-uncased') 
text = "This movie was amazing" 
inputs = tokenizer(text,return_tensors='pt') 
outputs = model(**inputs) 
predictions = torch.argmax(outputs.logits,dim=1) 
print(predictions)

c:\Users\石天辰\.conda\envs\pytorch\lib\site-packages\transformers\tokenization_utils_base.py:1601: FutureWarning: `clean_up_tokenization_spaces` was not set. It will be set to `True` by default. This behavior will be depracted in transformers v4.45, and will be then set to `False` by default. For more details check this issue: https://github.com/huggingface/transformers/issues/31884
  warnings.warn(
Some weights of BertForSequenceClassification were not initialized from the model checkpoint at bert-base-uncased and are newly initialized: ['classifier.bias', 'classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.


tensor([0])


In [4]:
#可视化注意力权重
import torch
from transformers import BertModel, BertTokenizer

tokenizer = BertTokenizer.from_pretrained('bert-base-uncased')
model = BertModel.from_pretrained('bert-base-uncased')

text = "BERT's attention mechanism is fascinating."
inputs = tokenizer(text, return_tensors='pt', padding=True, truncation=True)
outputs = model(**inputs, output_attentions=True)

attention_weights = outputs.attentions
print(attention_weights)

BertSdpaSelfAttention is used but `torch.nn.functional.scaled_dot_product_attention` does not support non-absolute `position_embedding_type` or `output_attentions=True` or `head_mask`. Falling back to the manual attention implementation, but specifying the manual implementation will be required from Transformers version v5.0.0 onwards. This warning can be removed using the argument `attn_implementation="eager"` when loading the model.


(tensor([[[[7.0430e-02, 4.7734e-02, 4.5779e-02,  ..., 9.7265e-02,
           1.3927e-01, 3.5823e-01],
          [3.6679e-02, 8.6646e-02, 4.3685e-02,  ..., 2.3391e-01,
           3.7266e-02, 6.5047e-02],
          [8.5532e-02, 1.3269e-01, 3.7626e-02,  ..., 1.2145e-01,
           1.1870e-01, 1.3301e-01],
          ...,
          [5.4352e-02, 1.2452e-01, 1.4481e-01,  ..., 1.2920e-01,
           1.0262e-01, 1.0715e-01],
          [8.2242e-02, 1.0184e-01, 9.4826e-02,  ..., 9.6448e-02,
           1.5859e-01, 1.1109e-01],
          [9.6005e-02, 6.8182e-02, 6.3413e-02,  ..., 1.3608e-01,
           1.7070e-01, 1.8861e-01]],

         [[6.8129e-01, 9.2499e-03, 2.2069e-01,  ..., 5.5413e-03,
           3.5570e-02, 7.2794e-03],
          [2.3929e-01, 5.2402e-02, 8.9530e-02,  ..., 1.1060e-01,
           1.2288e-01, 1.3781e-01],
          [1.9622e-02, 1.6688e-01, 1.2318e-02,  ..., 2.9411e-01,
           1.1144e-01, 3.4867e-02],
          ...,
          [1.6697e-01, 9.8040e-02, 3.0382e-02,  ..., 7.042

In [5]:
#预训练和 MLM 
from transformers import BertForMaskedLM, BertTokenizer
import torch

tokenizer = BertTokenizer.from_pretrained('bert-base-uncased')
model = BertForMaskedLM.from_pretrained('bert-base-uncased')

text = "BERT is a powerful language model."
inputs = tokenizer(text, return_tensors='pt', padding=True, truncation=True, add_special_tokens=True)
outputs = model(**inputs, labels=inputs['input_ids'])

loss = outputs.loss
print(loss)

Some weights of the model checkpoint at bert-base-uncased were not used when initializing BertForMaskedLM: ['bert.pooler.dense.bias', 'bert.pooler.dense.weight', 'cls.seq_relationship.bias', 'cls.seq_relationship.weight']
- This IS expected if you are initializing BertForMaskedLM from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing BertForMaskedLM from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).


tensor(4.0929, grad_fn=<NllLossBackward0>)


In [6]:
#使用 Hugging Face Transformer 提取单词嵌入 
from transformers import BertTokenizer, BertModel
import torch

tokenizer = BertTokenizer.from_pretrained('bert-base-uncased')
model = BertModel.from_pretrained('bert-base-uncased')

text = "BERT embeddings are fascinating."
inputs = tokenizer(text, return_tensors='pt', padding=True, truncation=True, add_special_tokens=True)
outputs = model(**inputs)

word_embeddings = outputs.last_hidden_state
print(word_embeddings)

tensor([[[-0.1094,  0.2831, -0.2219,  ..., -0.4116,  0.2604,  0.4303],
         [ 0.3717,  0.0461,  0.3014,  ..., -0.2603, -0.2263,  0.0782],
         [-0.2072,  0.3525, -0.2668,  ..., -0.0065, -0.6920, -0.0067],
         ...,
         [ 0.5834,  0.4004,  0.4881,  ..., -0.1181,  0.2630, -0.1225],
         [ 0.0716, -0.2377, -0.3874,  ...,  0.2981,  0.0436, -0.6352],
         [ 0.8747,  0.4112, -0.3423,  ...,  0.2614, -0.4867, -0.2898]]],
       grad_fn=<NativeLayerNormBackward0>)


In [8]:
from transformers import BertForSequenceClassification, BertTokenizer
import torch

tokenizer = BertTokenizer.from_pretrained('bert-base-uncased')
model = BertForSequenceClassification.from_pretrained('bert-base-uncased')

text = "Advanced fine-tuning with BERT."
inputs = tokenizer(text, return_tensors='pt', padding=True, truncation=True)
outputs = model(**inputs, output_hidden_states=True)

intermediate_layer = outputs.hidden_states[6]  # 7th layer
print(intermediate_layer)

c:\Users\石天辰\.conda\envs\pytorch\lib\site-packages\transformers\tokenization_utils_base.py:1601: FutureWarning: `clean_up_tokenization_spaces` was not set. It will be set to `True` by default. This behavior will be depracted in transformers v4.45, and will be then set to `False` by default. For more details check this issue: https://github.com/huggingface/transformers/issues/31884
  warnings.warn(
Some weights of BertForSequenceClassification were not initialized from the model checkpoint at bert-base-uncased and are newly initialized: ['classifier.bias', 'classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.


tensor([[[-0.3527, -1.1815, -0.3027,  ..., -0.1794,  0.0872,  0.5573],
         [-0.3768,  0.1754,  0.3395,  ..., -0.0359,  0.2162, -1.2251],
         [ 1.8406, -0.6458,  0.5841,  ..., -0.7345,  0.7542, -0.1614],
         ...,
         [ 1.0414, -0.7009,  1.0362,  ...,  1.0581, -0.3068, -1.4171],
         [-0.8934, -0.8139, -0.3154,  ..., -0.3933, -0.6383,  0.0522],
         [ 0.0143, -0.0423, -0.0131,  ...,  0.0044, -0.0140, -0.0394]]],
       grad_fn=<NativeLayerNormBackward0>)


In [9]:
from transformers import RobertaTokenizer, RobertaModel
import torch

tokenizer = RobertaTokenizer.from_pretrained('roberta-base')
model = RobertaModel.from_pretrained('roberta-base')

text = "RoBERTa is an advanced variant of BERT."
inputs = tokenizer(text, return_tensors='pt', padding=True, truncation=True)
outputs = model(**inputs)

embeddings = outputs.last_hidden_state
print(embeddings)

c:\Users\石天辰\.conda\envs\pytorch\lib\site-packages\huggingface_hub\file_download.py:159: UserWarning: `huggingface_hub` cache-system uses symlinks by default to efficiently store duplicated files but your machine does not support them in C:\Users\石天辰\.cache\huggingface\hub\models--roberta-base. Caching files will still work but in a degraded version that might require more space on your disk. This warning can be disabled by setting the `HF_HUB_DISABLE_SYMLINKS_WARNING` environment variable. For more details, see https://huggingface.co/docs/huggingface_hub/how-to-cache#limitations.
To support symlinks on Windows, you either need to activate Developer Mode or to run Python as an administrator. In order to see activate developer mode, see this article: https://docs.microsoft.com/en-us/windows/apps/get-started/enable-your-device-for-development
  warnings.warn(message)
Some weights of RobertaModel were not initialized from the model checkpoint at roberta-base and are newly initialized: ['r

tensor([[[-0.0640,  0.1073, -0.0181,  ..., -0.0383, -0.0555, -0.0151],
         [-0.0647,  0.0450, -0.0528,  ...,  0.0814, -0.1633, -0.0284],
         [ 0.0398,  0.0657, -0.1046,  ..., -0.1364, -0.0650,  0.0560],
         ...,
         [ 0.0273,  0.0271, -0.0042,  ..., -0.1554, -0.0037,  0.1105],
         [-0.0560,  0.1078, -0.0385,  ..., -0.0619, -0.0614, -0.0363],
         [ 0.0064,  0.1383,  0.0011,  ...,  0.0994, -0.0593,  0.0169]]],
       grad_fn=<NativeLayerNormBackward0>)


In [10]:
#使用 BERT 和 Hugging Face Transformers 进行文本摘要 
from transformers import BertTokenizer, BertForSequenceClassification
import torch

tokenizer = BertTokenizer.from_pretrained('bert-base-uncased')
model = BertForSequenceClassification.from_pretrained('bert-base-uncased')

original_text = "Long text for summarization..."
inputs = tokenizer(original_text, return_tensors='pt', padding=True, truncation=True)

summary_logits = model(**inputs).logits
summary = tokenizer.decode(torch.argmax(summary_logits, dim=1))
print("Summary:", summary)

Some weights of BertForSequenceClassification were not initialized from the model checkpoint at bert-base-uncased and are newly initialized: ['classifier.bias', 'classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.


Summary: [PAD]


In [11]:
#使用 BERT 处理长文本 
max_seq_length = 512 
text = "Long text to be handled..." 
text_chunks = [text[i:i+max_seq_length] for i in range(0,len(text),max_seq_length)] 
for chunk in text_chunks:
    inputs = tokenizer(chunk,return_tensors='pt',padding=True,truncation=True) 
    outputs = model(**inputs) 
    

#资源密集型计算 
BERT 模型，尤其是较大的模型，对计算要求很高。要解决此问题，您可以使用混合精度训练等技术，从而减少内存消耗并加快训练速度。此外，您可以考虑使用较小的模型或云资源来完成繁重的任务。

In [ ]:
from torch.cuda.amp import autocast,GradScaler 
scaler = GradScaler() 
with autocast():
    inputs = tokenizer(text,return_tensors='pt',padding=True,truncation=True) 
    outputs = model(**inputs) 
    print(type(outputs))  # 查看outputs的类型
    
    if hasattr(outputs, 'loss'):
        loss = outputs.loss  
    else:
        raise ValueError("Model output does not contain a 'loss' attribute.")
    loss = outputs.loss 
scaler.scale(loss).backward() 
scaler.step(optimizer) 
scaler.update()

域适应 

虽然 BERT 用途广泛，但它在某些域中可能无法发挥最佳性能。要解决此问题，请对特定于域的数据微调 BERT。通过将其暴露给来自目标域的文本，BERT 将学会理解特定于该字段的细微差别和术语。

In [ ]:
domain_data = load_domain_specific_data()  # Load domain-specific dataset
domain_model = BertForSequenceClassification.from_pretrained('bert-base-uncased')
train_domain(domain_model, domain_data)

带有 Hugging Face Transformer 的多语言 BERT

In [15]:
from transformers import BertTokenizer, BertModel
import torch

tokenizer = BertTokenizer.from_pretrained('bert-base-multilingual-cased')
model = BertModel.from_pretrained('bert-base-multilingual-cased')

text = "BERT understands multiple languages!"
inputs = tokenizer(text, return_tensors='pt', padding=True, truncation=True)
outputs = model(**inputs)

embeddings = outputs.last_hidden_state
print(embeddings)

c:\Users\石天辰\.conda\envs\pytorch\lib\site-packages\huggingface_hub\file_download.py:159: UserWarning: `huggingface_hub` cache-system uses symlinks by default to efficiently store duplicated files but your machine does not support them in C:\Users\石天辰\.cache\huggingface\hub\models--bert-base-multilingual-cased. Caching files will still work but in a degraded version that might require more space on your disk. This warning can be disabled by setting the `HF_HUB_DISABLE_SYMLINKS_WARNING` environment variable. For more details, see https://huggingface.co/docs/huggingface_hub/how-to-cache#limitations.
To support symlinks on Windows, you either need to activate Developer Mode or to run Python as an administrator. In order to see activate developer mode, see this article: https://docs.microsoft.com/en-us/windows/apps/get-started/enable-your-device-for-development
  warnings.warn(message)
c:\Users\石天辰\.conda\envs\pytorch\lib\site-packages\transformers\tokenization_utils_base.py:1601: FutureWar

tensor([[[-0.1740, -0.3340, -0.6609,  ...,  0.4222,  0.3596, -0.0141],
         [ 0.4543,  0.1575, -0.2935,  ..., -0.0887,  0.3577,  0.3759],
         [ 0.7044,  0.1681, -0.1217,  ...,  0.9337,  0.4014, -0.2957],
         ...,
         [-0.2753, -0.4430, -0.5777,  ...,  0.4702,  0.0326, -0.1780],
         [-0.4562, -0.2416, -0.9867,  ...,  0.1909,  0.5182, -0.1369],
         [-0.4752, -0.3440, -0.5101,  ...,  0.0674,  0.5783, -0.1292]]],
       grad_fn=<NativeLayerNormBackward0>)


使用 BERT 进行终身学习

In [ ]:
from transformers import BertForSequenceClassification, BertTokenizer
import torch

tokenizer = BertTokenizer.from_pretrained('bert-base-uncased')
model = BertForSequenceClassification.from_pretrained('bert-base-uncased')

new_data = load_latest_data()  # Load updated dataset
for epoch in range(epochs):
    train_lifelong(model, new_data)

In [17]:
#加载预训练的 BERT 模型 
from transformers import BertForSequenceClassification, BertTokenizer

model = BertForSequenceClassification.from_pretrained('bert-base-uncased')
tokenizer = BertTokenizer.from_pretrained('bert-base-uncased')
# 文本分词和编码
# BERT 以分词形式处理文本。您需要使用 tokenizer 对文本进行分词，并为模型对其进行编码：
text = "BERT is amazing!"
inputs = tokenizer(text, return_tensors='pt', padding=True, truncation=True)
#进行预测 
outputs = model(**inputs)
predicted_class = torch.argmax(outputs.logits).item()
print("Predicted Sentiment Class:", predicted_class)

Some weights of BertForSequenceClassification were not initialized from the model checkpoint at bert-base-uncased and are newly initialized: ['classifier.bias', 'classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.


Predicted Sentiment Class: 1


In [18]:
#微调 BERT 
from transformers import BertForSequenceClassification, BertTokenizer, AdamW
import torch

model = BertForSequenceClassification.from_pretrained('bert-base-uncased')
tokenizer = BertTokenizer.from_pretrained('bert-base-uncased')

text = "Sample text for training."
label = 1  # Assuming positive sentiment

inputs = tokenizer(text, return_tensors='pt', padding=True, truncation=True)
outputs = model(**inputs, labels=torch.tensor([label]))

loss = outputs.loss
optimizer = AdamW(model.parameters(), lr=1e-5)
loss.backward()
optimizer.step()

Some weights of BertForSequenceClassification were not initialized from the model checkpoint at bert-base-uncased and are newly initialized: ['classifier.bias', 'classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
c:\Users\石天辰\.conda\envs\pytorch\lib\site-packages\transformers\optimization.py:591: FutureWarning: This implementation of AdamW is deprecated and will be removed in a future version. Use the PyTorch implementation torch.optim.AdamW instead, or set `no_deprecation_warning=True` to disable this warning
  warnings.warn(
